image: alpine:latest
pages:
  stage: deploy
  before_script:
  - apk update && apk add brotli git
  script:
  - ./mk.sh
  - find . -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|json\|dz\|index\|csv\)$\|.*/LICENSE$' -exec gzip -9 -f -k {} \;
  - find . -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|json\|dz\|index\|csv\)$\|.*/LICENSE$' -exec brotli -f -k {} \;
  - mkdir -p .public
  - mv -t .public *
  - mv .public public
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - master
