image: alpine:latest
pages:
  stage: deploy
  before_script:
  - apk update && apk add brotli git gawk
  script:
  - ./mk.sh
  - mkdir -p .public
  - mv -t .public *
  - mv .public public
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - master
